
source 'git@192.168.28.216:zhangyao/TZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TestForRouter_Example' do
  pod 'TestForRouter', :path => '../'

  target 'TestForRouter_Tests' do
    inherit! :search_paths

    
  end
end
